# Server settings
server:
  port: 8080
  address: 0.0.0.0
# DATASOURCE
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhanghanlin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 最大连接池数量
    maxActive: 20
    # 初始化时建立物理连接的个数
    initialSize: 1
    # 获取连接时最大等待时间,单位毫秒.配置了maxWait之后,缺省启用公平锁,并发效率会有所下降
    maxWait: 60000
    # Destroy线程会检测连接的间隔时间
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sq
    validationQuery: select 'x'
    # 建议配置为true，不影响性能，并且保证安全性
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement,也就是PSCache
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,log4j
    connectionLogEnabled: true
    dataSourceLogEnabled: true
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.demo.boot.entity
# LOGGING
logging:
  level:
    com:
      demo.boot: INFO
      alibaba: WARN
    org:
      springframework: WARN
      apache: WARN
      hibernate: WARN
      thymeleaf: WARN
    net:
      sf:
        ehcache: WARN